name: Trigger Workflow

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  trigger-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        env:
          SECRET_PAT: ${{ secrets.SECRET_PAT }}
          ORG: ${{ secrets.ORG }}
          REPO: ${{ secrets.REPO }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $SECRET_PAT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$ORG/$REPO/actions/workflows/webhook-pr-trigger.yml/dispatches \
            -d '{"ref":"main"}'
